export const LOGGED = 'LOGGED';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_GRECAPTCHA = 'SET_GRECAPTCHA';
export const SET_LOADING_DATA = 'SET_LOADING_DATA';
export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const RECEIVE_TOKEN_SUCCESS = 'RECEIVE_TOKEN';
export const RECEIVE_TOKEN_FAIL = 'RECEIVE_TOKEN';
